apiVersion: v1
kind: Service
metadata:
  name: ininrmonnetapp
spec:
  selector:
    app: ininrmonnetapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30638
  type: NodePort
